name: CI

on:
  push:
    branches:
      - main

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Semantic release
        run: npx semantic-release
        env:
          CI_COMMIT_BRANCH: ${{ github.ref }}
          CI_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
