name: Release
on:
  workflow_dispatch:
jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Release
        #working-directory: ./.release
        run: |
          npm cache clear
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}